### ISSUE TITLE
Remove case sensitive input

### ISSUE THREAD

**Issue by Dohxis** [edve98/Terminal-Play#2]
I think we don't need to have our input case-sensitive. It can be confusing and lead to all sorts of problems for players. Considering there are no other game engine supporting case-sensitive input, we don't need it either, besides code will be way more cleaner.

**Comment by vodpox** [comment]
I don't think there's need to remove it. Right now default is case-insensitive input. That means that users will use that only if they understand it and need it. For code cleanness: case sensitivity doesn't take up much code (although it might be wise to separate capital letters in KeyCode enum).

**Comment by Dohxis** [comment]
But that enumeration looks awful :disappointed:

**Comment by edve98** [comment]
Fine.
