### ISSUE TITLE
Examples don't compile

### ISSUE THREAD

**Issue by Dohxis** [edve98/Terminal-Play#6]
`examples/simple demo` don't compile giving following error

```
./main.cpp: In member function ‘virtual void ExampleScene::draw()’:
./main.cpp:40:19: error: ‘class tplay::Graphics’ has no member named ‘setCameraCoordinates’
    game->graphics.setCameraCoordinates(x - (game->graphics.getTerminalSizeX() / 2), y - (game->graphics.getTerminalSizeY() / 2));
                   ^~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:7: build] Error 1
```

Line 40 causes this error

```
game->graphics.setCameraCoordinates(x - (game->graphics.getTerminalSizeX() / 2), y - (game->graphics.getTerminalSizeY() / 2));
```

and if commented out I got `segmentation fault`.

**Comment by vodpox** [comment]
Simple demo should now compile (I forgot to update it when I changed how camera works). Segmentation fault will not be thrown if you don't assign any camera after Camera functionality is finalized (you can look forward to that in 1.0.0 release which should come in a few weeks).
